import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase/client";

export async function GET() {
  const { data, error } = await supabase
    .from("brew_batches")
    .select("*, recipes(beer_name, brewery, brew_time_weeks, expected_yield_bbl), batch_status_history(*), planned_allocations(*)")
    .order("planned_brew_date", { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data);
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { beer_name, planned_brew_date, expected_delivery_date, volume_bbl, turns, status = "planning", notes, recipe_id } = body;

  if (!recipe_id) return NextResponse.json({ error: "recipe_id is required" }, { status: 400 });

  // batch_number auto-generated by DB trigger
  const { data: batch, error: batchErr } = await supabase
    .from("brew_batches")
    .insert({ beer_name, planned_brew_date, expected_delivery_date: expected_delivery_date || null, volume_bbl, turns, status, notes, recipe_id })
    .select()
    .single();

  if (batchErr) return NextResponse.json({ error: batchErr.message }, { status: 500 });

  // Log initial status
  await supabase.from("batch_status_history").insert({
    batch_id: batch.id,
    status: batch.status,
    note: "Batch created",
  });

  // Log stock consumption for each recipe ingredient
  const { data: recipeIngredients } = await supabase
    .from("recipe_ingredients")
    .select("ingredient_id, quantity_per_bbl")
    .eq("recipe_id", recipe_id);

  if (recipeIngredients?.length) {
    const adjustments = recipeIngredients.map((ri) => ({
      ingredient_id: ri.ingredient_id,
      quantity: -(ri.quantity_per_bbl * volume_bbl),
      type: "batch_use" as const,
      note: `Used in ${batch.batch_number}: ${batch.beer_name}`,
      batch_id: batch.id,
    }));
    await supabase.from("stock_adjustments").insert(adjustments);
    for (const adj of adjustments) {
      await supabase.rpc("adjust_ingredient_stock", { p_id: adj.ingredient_id, p_delta: adj.quantity });
    }
  }

  const { data, error } = await supabase
    .from("brew_batches")
    .select("*, recipes(beer_name, brewery, brew_time_weeks, expected_yield_bbl), batch_status_history(*), planned_allocations(*)")
    .eq("id", batch.id)
    .single();

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data, { status: 201 });
}
