-- ramp_bank_ledger -> bank_ledger
--
-- 45 of the 58 rows are source='plaid'; only 13 are source='ramp'. The CHECK
-- constraint has admitted both since 20260916090000_bank_ledger_plaid_source.sql.
-- The name says this is a Ramp table. It is not, and it is the table the balance
-- sheet and cash-flow work touch most, so the misnomer costs real time.
--
-- Postgres renames the table but nothing attached to it, so every index,
-- constraint and trigger is renamed here too. Leaving `ramp_bank_ledger_pkey`
-- on a table called `bank_ledger` would relocate the confusion, not remove it.
--
-- NOT renamed, deliberately:
--   * the `source` column and its values 'ramp' / 'plaid' -- both are real sources
--   * `bank_ledger_gl_rules`                              -- already correct
--   * policies "grant read" / "grant write"               -- table-agnostic names
--     generated by apply_grant_policies() in 20261003090000_rls_close_authenticated_read_gaps.sql
--   * public.update_updated_at()                          -- shared by every table
--     with an updated_at column, since 20261001090005_canonical_updated_at_trigger.sql

alter table public.ramp_bank_ledger rename to bank_ledger;

-- ── Indexes not backed by a constraint ───────────────────────────────────────
alter index public.idx_ramp_bank_ledger_excluded         rename to idx_bank_ledger_excluded;
alter index public.idx_ramp_bank_ledger_flow_type        rename to idx_bank_ledger_flow_type;
alter index public.idx_ramp_bank_ledger_source_account   rename to idx_bank_ledger_source_account;
alter index public.idx_ramp_bank_ledger_txn_date         rename to idx_bank_ledger_txn_date;
alter index public.ramp_bank_ledger_counterparty_key_idx rename to bank_ledger_counterparty_key_idx;
-- Added by 20261001090003_index_foreign_keys_on_growing_tables.sql
alter index public.ramp_bank_ledger_chart_of_accounts_id_idx rename to bank_ledger_chart_of_accounts_id_idx;
alter index public.ramp_bank_ledger_connection_id_idx        rename to bank_ledger_connection_id_idx;

-- ── Constraints (renaming pkey/unique also renames the backing index) ────────
alter table public.bank_ledger rename constraint ramp_bank_ledger_pkey                    to bank_ledger_pkey;
alter table public.bank_ledger rename constraint ramp_bank_ledger_source_txn_unique       to bank_ledger_source_txn_unique;
alter table public.bank_ledger rename constraint ramp_bank_ledger_source_check            to bank_ledger_source_check;
alter table public.bank_ledger rename constraint ramp_bank_ledger_flow_type_check         to bank_ledger_flow_type_check;
alter table public.bank_ledger rename constraint ramp_bank_ledger_mapping_source_check    to bank_ledger_mapping_source_check;
alter table public.bank_ledger rename constraint ramp_bank_ledger_chart_of_accounts_id_fkey to bank_ledger_chart_of_accounts_id_fkey;
alter table public.bank_ledger rename constraint ramp_bank_ledger_connection_id_fkey        to bank_ledger_connection_id_fkey;

-- ── Trigger ──────────────────────────────────────────────────────────────────
alter trigger ramp_bank_ledger_updated_at on public.bank_ledger rename to bank_ledger_updated_at;

-- ── Compatibility shim ───────────────────────────────────────────────────────
-- The migration lands before the code that stops using the old name finishes
-- deploying, so `ramp_bank_ledger` has to keep answering for that window.
--
-- security_invoker = true is load-bearing. A view defaults to the *definer's*
-- rights, which would read straight past the row-level security that
-- 20261003090000_rls_close_authenticated_read_gaps.sql just put on this table --
-- turning a rename into a data leak. With invoker rights the caller's policies
-- still apply, so the shim is exactly as restricted as the table.
create view public.ramp_bank_ledger with (security_invoker = true) as
  select * from public.bank_ledger;

comment on view public.ramp_bank_ledger is
  'Deprecated compatibility shim for the rename to bank_ledger. Drop once every '
  'deployed environment is off the old name. A simple select * view is '
  'auto-updatable, so plain INSERT/UPDATE/DELETE pass through; ON CONFLICT '
  'upserts do NOT, because a view exposes no unique index to infer against.';

-- Mirror the table's grants so the shim neither adds nor removes access.
grant select, insert, update, delete, truncate, references, trigger
  on public.ramp_bank_ledger to anon, authenticated, service_role, postgres;
